---
title: "LythrumDisplayInd"
author: "Dale Moskoff"
date: "20/04/2021"
output: html_document
---

# Setup

```{r data setup}
library(dplyr)
library(tidyr)
library(mgcv)
library(ggplot2)
library(moments)
library(readr)
library(zoo)

dat<-read.csv("./data/LythrumDisplay2008.csv")
dat<-dat[dat$Num!=187,]
dat<-dat[dat$Num!=440,]
LythrumDisplayInd<-dplyr :: select (dat,-Row,-End,-(d0:d60)) # Basic dataframe WITHOUT moments (will be final data frame in the end)


## Manipulate original dataset to include absolute day of flowering
Days<-names(dat)[grep("d[0-9]",names(dat))] # Vector of names
Flwr<-dat %>% gather(all_of(Days),key="RelDay",value="OpFlwr") # Rearrange
Flwr$RelDay<-as.numeric(gsub("d","",Flwr$RelDay)) # Remove 'd' from day
Flwr$AbsDay<-Flwr$RelDay+Flwr$Start # Add absolute day
```

# Convert to long format

```{r long format}

Ind<-unique(Flwr$Num) 

##Extend AbsDay to be 0:125 with OpFlwr values being NA on added rows of AbsDay.
MasterData<-matrix(nrow=0,ncol=3)
colnames(MasterData)<-c("AbsDay","OpFlwr","Individual")
for (i in 1:length(Ind)) {
  Focal<-subset(Flwr,Flwr$Num==Ind[i])
  Start<-min(Focal$AbsDay)-1 #Day that flowering was observed to start.
  End<-max(Focal$AbsDay)+1 #Day that flowering was observed to end.
    
  if (End == 126|End == 125) { #Trouble shooting for when flowering end date was 125 or 126.
    OpFlwr<-c(rep(NA,length(0:Start)),Focal$OpFlwr) #rep 0 for OpFlwr until start of flowering, then use observed values of OpFlwr
    AbsDay<-c(0:Start,Focal$AbsDay)
  } else {
    OpFlwr<-c(rep(NA,length(0:Start)),Focal$OpFlwr,rep(NA,length(End:125)))#rep 0 for OpFlwr until start of flowering, then use observed values of OpFlwr until end of observed flowering, then rep 0
    OpFlwr<-c(rep(NA,length(0:Start)),Focal$OpFlwr,rep(NA,length(End:125)))
    AbsDay<-c(0:Start,Focal$AbsDay,End:125)
  }
  Individual<-c(rep(Ind[i],length(AbsDay))) #Individual column
  NewData<-data.frame(AbsDay,OpFlwr,Individual) #New data frame for each individual
  MasterData<-rbind(MasterData,NewData) #New data frame containing information for all individuals
  #print(Ind[i])
}
```


# Impute between census dates

```{r}
PredictDay<-function(Num,df){
  AbsDay<-c(0:125)
  PredDay<-rep(NA,length(AbsDay))
  PredDay[df$AbsDay[df$Individual==Num]+1]<-df$OpFlwr[df$Individual==Num] # Add observed flower counts to predday
# is.na(PredDay) # We have to remove NAs at the beginning and end of the observed OpFlwr values to get proper LI inputs. 
  if(is.na(PredDay[1])){
    PredDay[1]<-0
  }
  
  if(is.na(PredDay[length(PredDay)])){
    PredDay[length(PredDay)]<-0
  }
  
  PredDay<-na.approx(PredDay,na.rm=F)
  PredDay[is.na(PredDay)]<-0

  return(PredDay)
}

## Put new extended and imputed data points into long-form data frame.
df3<-matrix(ncol=5,nrow=0)
colnames(df3)<-c("Flowers","Individual.x","Days","OpFlwr","Individual.y")
Ind<-unique(MasterData$Individual)
Days<-c()
Individual<-c()
Flowers<-c()
for( j in 1:length(Ind)){
  FocalFrame<-MasterData[MasterData$Individual==Ind[j],]
  Flowers<-PredictDay(Num=Ind[j],df=MasterData)#Here use j to subset each individual in the individual ID vector. 
  Individual<-rep(Ind[j], times=length(0:125)) #Here to identify the individual, we also need to subset the Ind vector instead. 
  Days<-0:125
  df1<-data.frame(Flowers,Individual,Days)
  df2<-df1 %>% left_join(FocalFrame,by=c("Days"="AbsDay")) #Joining new data frame (with GAM predictions) with raw data frame.
  df3<-rbind(df3,df2)
}
```

# Find moments of standardized data and troubleshoot missing data

```{r find moments of standardized data}

#Find moments.
DisplayInd<-data.frame()

##New moments for-loop with new dataset. 
for(j in 1:length(Ind)){
  Focal<-df3[df3$Individual.x==Ind[j],]
  pDays<-Focal$OpFlwr/sum(Focal$OpFlwr,na.rm=TRUE) # Proportion of total open flowers open on each day 
  WeightDays<-Focal$Days*pDays # Weight days by their relative contributions to the mating pool.
  Mean<-sum(WeightDays,na.rm=TRUE) # Mean value.
  Var<-sum((WeightDays-Mean)^2*pDays,na.rm=TRUE) # Instead of dividing by the sample size, we multiply by the fractional weighting of pDays
  
  CoeffVar<-Var/(Mean)
  CoeffSkew<-sum((WeightDays-Mean)^3*pDays,na.rm=TRUE)/sqrt(Var)^3
  CoeffKurt<-sum((WeightDays-Mean)^4*pDays,na.rm=TRUE)/sqrt(Var)^4

  DisplayInd<-rbind(DisplayInd,
                    c(Ind[j], Mean, Var, CoeffSkew, CoeffKurt))
  
} 
names(DisplayInd)<-c("Num","Peak","Var","Skew","Kurt")

LythrumDisplayInd <- full_join(LythrumDisplayInd,DisplayInd,by="Num")

### Troubleshooting. ###

LythrumDisplayInd<-LythrumDisplayInd[!is.nan(LythrumDisplayInd$Kurt),]#Remove individuals with NaN values for Kurtosis (and by extension skewness -- same individuals also have values of 0 for variance) from dataset. 
subset(LythrumDisplayInd,is.nan(Kurt)) #Double check.

#Add in missing duration values.
LythrumDisplayInd[is.na(LythrumDisplayInd$Duration),] #Check missing values.
Ind2<-LythrumDisplayInd$Num
for(j in 1:length(Ind2)){
  Focal<-subset(LythrumDisplayInd,LythrumDisplayInd$Num==Ind2[j]) 
  if (is.na(Focal$Duration)) {
    Focal2<-subset(Flwr,Flwr$Num==Focal$Num)
    Start<-min(Focal2$AbsDay, na.rm=T)
    End<-max(Focal2$AbsDay, na.rm=T)
    Dur<-End-Start
    LythrumDisplayInd$Duration[LythrumDisplayInd$Num==Ind2[j]]<-Dur
    print("Yes")
  } else {
    print("No")
  }
}  ## Calculate missing duration values from 5-day census data and replace missing values with calculated values.
LythrumDisplayInd[is.na(LythrumDisplayInd$Duration),] #Check that missing values have now been replaced with calculated duration.

### Export dataset. ###

write.csv(LythrumDisplayInd,"./data/FloralDisplayInd.csv",row.names=F)

```

```{r population means}
PopCode<-unique(LythrumDisplayInd$Pop)

# Calculate population means
PopMeans<-data.frame()
##Find population averages for each moment.
for(j in 1:length(PopCode)){
  Focal<-subset(LythrumDisplayInd,LythrumDisplayInd$Pop==PopCode[j])

  Pop<-unique(Focal$Pop)
  Latitude<-unique(Focal$Lat)

  TotFlwr<-mean(Focal$TotFlwr, na.rm=T)
  Start<-mean(Focal$Start,na.rm=TRUE)
  End<-mean(Focal$Start+Focal$Duration,na.rm=TRUE)
  Duration<-mean(Focal$Duration,na.rm=TRUE)
  Peak<-mean(Focal$Peak,na.rm=TRUE)
  Var<-mean(Focal$Var,na.rm=TRUE)
  Skew<-mean(Focal$Skew,na.rm=TRUE)
  Kurt<-mean(Focal$Kurt,na.rm=TRUE)
  
  PopMeans<-rbind(PopMeans, c(
                  Pop, Latitude, 
                  TotFlwr, Start, End, Duration,
                  Peak, Var, Skew, Kurt))

  Pop<-Latitude<-TotFlwr<-Start<-End<-Duration<-PeakS<-VarS<-SkewS<-KurtS<-NA
} 

names(PopMeans)<-c("Pop", "Latitude", "TotFlwr", 
                   "Start", "End","Duration",
                   "Peak", "Var", "Skew", "Kurt")

write.csv(PopMeans,"./data/FloralDisplayPop.csv",row.names=F)

```

```{r within-population variation}
## Calculate within-population sums of total flowers/day.
# Since census days started from day of first flower, observation days are different for each individual. I think a clearer approximation of the total number of open flowers/day can be obtained by summing open flower values including imputed values. 
df4<-c()
PopSums<-matrix(ncol=3,nrow=0)
colnames(PopSums)<-c("PopCode","Days","FlwrSum")
PopCode<-unique(LythrumDisplayInd$Pop)
for(j in 1:length(PopCode)){
  Focal<-subset(LythrumDisplayInd,LythrumDisplayInd$Pop==PopCode[j])
  Focal2<-subset(df3, Individual.x %in% Focal$Num)
  df4<-Focal2 %>% group_by(Days) %>% summarize(Flowers=sum(Flowers))
  Pop<-rep(PopCode[j],length(Days)) # Population code column
  NewData<-data.frame(Pop,Days,Flowers) # New dataset from Focal.
  PopSums<-rbind(PopSums,NewData) # Final dataset.
}

write.csv(PopSums,"./data/PopulationOpFlwrTotals.csv",row.names=F)
```

```{r flowering schedule moments based on total flowers/day within populations}
#Find moments.
DisplayPop<-data.frame()

##New moments for-loop with new dataset. 
for(j in 1:length(PopCode)){
  Focal<-PopSums[PopSums$Pop==PopCode[j],]
  pDays<-Focal$Flowers/sum(Focal$Flowers,na.rm=TRUE) # Proportion of total open flowers open on each day 
  WeightDays<-Focal$Days*pDays # Weight days by their relative contributions to the mating pool.
  Mean<-sum(WeightDays,na.rm=TRUE) # Mean value.
  Var<-sum((WeightDays-Mean)^2*pDays,na.rm=TRUE) # Instead of dividing by the sample size, we multiply by the fractional weighting of pDays
  
  CoeffVar<-Var/(Mean)
  CoeffSkew<-sum((WeightDays-Mean)^3*pDays,na.rm=TRUE)/sqrt(Var)^3
  CoeffKurt<-sum((WeightDays-Mean)^4*pDays,na.rm=TRUE)/sqrt(Var)^4

  DisplayPop<-rbind(DisplayPop,
                    c(PopCode[j], Mean, Var, CoeffSkew, CoeffKurt)) # The population code is strangely concatenating as a number and not the actual population code.
  
} 
names(DisplayPop)<-c("Pop","Peak","Var","Skew","Kurt")


```