---
title: "Floral Display Graphs"
author: "Dale Moskoff"
date: "22/04/2021"
output: html_document
---

# Setup

```{r data setup}
dat<-read.csv("./FloralDisplayPop.csv") # Latitudes of population origin were added to the csv file manually.
library(ggplot2)
library(dplyr)

theme_custom<-function(base_size = 24, base_family = ""){
  theme_bw(base_size = base_size, base_family = base_family) %+replace% 
    theme(axis.text = element_text(size = rel(0.8),colour="black"),
          axis.ticks = element_line(colour = "black"), 
          legend.position = "none",
          panel.border = element_rect(fill = NA, colour = NA), 
          panel.grid.major = element_line(colour = NA,size = 0), 
          panel.grid.minor = element_line(colour = NA,size = 0), 
          axis.line = element_line(colour ="black")
    )
}
```

# Common Metrics

```{r}
#Julian day first flower x Latitude
FirstFlwr<- ggplot() + geom_point(data=dat,mapping=aes(x=Latitude,y=MeanSD)) + labs(x="Latitude",y="Flowering Start Date",title="Start Date of Flowering Schedule by Latitude") + theme_custom() + geom_abline(intercept=142.861,slope=-2.769,colour="red")

FirstFlwr

reg4<-lm(MeanSD~Latitude,data=dat)
summary(reg4)


#Duration x Latitude
Duration<- ggplot() + geom_point(data=dat,mapping=aes(x=Latitude,y=MeanDuration)) + labs(x="Latitude",y="Flowering Duration",title="Duration of Flowering Schedule by Latitude") + theme_custom()

Duration

reg5<-lm(MeanDuration~Latitude,data=dat)
summary(reg5)

#End Date x Latitude
EndDate<-ggplot() + geom_point(data=dat,mapping=aes(x=Latitude,y=MeanEnd)) + labs(x="Latitude",y="Flowering End Date",title="End Date of Flowering Schedule by Latitude") + theme_custom() + geom_abline(intercept=193.986,slope=-3.008,colour="red")

EndDate

reg6<-lm(MeanEnd~Latitude,data=dat)
summary(reg6)

```



# Standardized Curve

(Area under flowering schedule curve = 1)

```{r standardized data graphs}
# Variance x Latitude
VarST<- ggplot() + geom_point(data=dat,mapping=aes(x=Latitude,y=MeanVarianceSTD)) + labs(x="Latitude",y="Variance",title="Variance of Flowering Schedule by Latitude (Standardized Data)") + theme_custom() + geom_abline(intercept=98.988 ,slope=-1.698,colour="red")

VarST

reg1<-lm(MeanVarianceSTD~Latitude,data=dat)
summary(reg1)

#Skew x Latitude
SkewST<- ggplot() + geom_point(data=dat,mapping=aes(x=Latitude,y=MeanSkewnessSTD)) + labs(x="Latitude",y="Skewness",title="Skewness of Flowering Schedule by Latitude (Standardized Data)") + theme_custom() + geom_abline(intercept=-8829.4,slope=174.4,colour="red")

SkewST

reg2<-lm(MeanSkewnessSTD~Latitude,data=dat)
summary(reg2)

#Kurtosis x Latitude
KurtST<- ggplot() + geom_point(data=dat,mapping=aes(x=Latitude,y=MeanKurtosisSTD)) + labs(x="Latitude",y="Kurtosis",title="Kurtosis of Flowering Schedule by Latitude (Standardized Data)") + theme_custom() + geom_abline(intercept=502509,slope=-10353,colour="red")

KurtST

reg3<-lm(MeanKurtosisSTD~Latitude,data=dat)
summary(reg3)
```

# Raw curves

(Area under flowering schedule curves = total number of flowers produced)

```{r raw data graphs}
# Variance x Latitude
VarR<- ggplot() + geom_point(data=dat,mapping=aes(x=Latitude,y=MeanVariance)) + labs(x="Latitude",y="Variance",title="Variance of Flowering Schedule by Latitude (Raw Data)") + theme(legend.position="none",plot.title = element_text(size=11))+ geom_abline(intercept=870.88,slope=-12.75,colour="red")
reg6<-lm(MeanVariance~Latitude,data=dat)
summary(reg6)

#Skew x Latitude
SkewR<- ggplot() + geom_point(data=dat,mapping=aes(x=Latitude,y=MeanSkewness)) + labs(x="Latitude",y="Skewness",title="Skewness of Flowering Schedule by Latitude (Raw Data)") + theme(legend.position="none",plot.title = element_text(size=11)) 
reg7<-lm(MeanSkewness~Latitude,data=dat)
summary(reg7)

#Kurtosis x Latitude
KurtR<- ggplot() + geom_point(data=dat,mapping=aes(x=Latitude,y=MeanKurtosis)) + labs(x="Latitude",y="Kurtosis",title="Kurtosis of Flowering Schedule by Latitude (Raw Data)") + theme(legend.position="none",plot.title = element_text(size=11)) 
reg8<-lm(MeanKurtosis~Latitude,data=dat)
summary(reg8)
```